// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehbvdyhpvbyberhkntbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoYnZkeWhwdmJ5YmVyaGtudGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzU3NzQsImV4cCI6MjA2NTU1MTc3NH0.n_a7OensAGF2DfyM3WLXuZlcHi8hTAlKgENAcX_nEHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);